version: "3.0"
services:
  api:
    tty: true
    build: "./containers/api"
    env_file: ".env"
    volumes:
      - ./containers/api/:/go/src/github.com/Ryutaro95/news-go/containers/api/
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -X GET http://localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    build: 
      context: "./containers/mysql"
    env_file: ".env"
    volumes: 
      - ./containers/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data: