version: "3.0"
services:
  api:
    tty: true
    build: "./containers/api"
    env_file: ".env"
    volumes:
      - ./containers/api/:/go/src/github.com/Ryutaro95/news-go/containers/api/
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -X GET http://localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5